
version: '3'
services:
  postgres.dev:
    build:
     context: ../../containers/postgres
     args:
      - AMBARI_DDL_URL_MYSQL=${AMBARI_DDL_URL_MYSQL}
    image: sarath4mec/postgres
    environment:
     - AMBARI_DDL_URL_MYSQL=${AMBARI_DDL_URL_MYSQL}
    hostname: postgres
    domainname: dev
