
version: '3'
services:
  mysql.dev:
    build:
     context: ../../containers/mysql
     args:
      - AMBARI_DDL_URL_MYSQL=${AMBARI_DDL_URL_MYSQL}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    image: sarath4mec/mysql
    environment:
     - AMBARI_DDL_URL_MYSQL=${AMBARI_DDL_URL_MYSQL}
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    hostname: mysql
    domainname: dev
