
version: '3'
services:
  postgres.dev:
    build:
     context: ../../containers/mysql
     args:
      - AMBARI_DDL_URL_MYSQL=${AMBARI_DDL_URL_MYSQL}
    image: sarath4mec/mysql
    environment:
     - AMBARI_DDL_URL_MYSQL=${AMBARI_DDL_URL_MYSQL}
    hostname: mysql
    domainname: dev
